2017-11-18 19:17:55 ERROR Input:24 - NumberFormatException
2017-11-18 19:21:19 ERROR Input:28 - File not found
2017-11-20 19:39:26 ERROR FileWorker:26 - File not found
2017-11-24 20:49:28 ERROR Serializer:26 - File not found
2017-11-24 20:50:26 ERROR Serializer:26 - File not found
2017-11-24 20:50:28 ERROR Serializer:26 - File not found
2017-11-24 20:50:30 ERROR Serializer:26 - File not found
2017-11-24 20:50:31 ERROR Serializer:26 - File not found
2017-11-24 20:52:50 ERROR Serializer:26 - File not found
2017-11-24 20:58:05 ERROR Serializer:26 - File not found
2017-11-26 18:31:19 ERROR Serializer:26 - File not found
2017-11-26 18:31:44 ERROR Serializer:26 - File not found
2017-11-26 18:38:50 ERROR Serializer:26 - File not found
2017-11-26 18:39:19 ERROR Input:24 - NumberFormatException
2017-11-27 12:11:23 ERROR Input:23 - NumberFormatException
2017-11-27 12:18:59 ERROR Input:23 - NumberFormatException
2017-11-27 18:48:20 ERROR Input:23 - For input string: "l"
2017-11-27 18:49:29 ERROR Input:23 - For input string: "k"
2017-11-27 18:54:14 ERROR Input:23 - java.lang.NumberFormatException: For input string: "k"
2017-11-27 18:54:37 ERROR Input:23 - java.lang.NumberFormatException: For input string: "l"
2017-11-27 18:55:30 ERROR Input:23 - For input string: "o"
2017-11-29 13:11:06 ERROR Serializer:24 - com.senla.entity.Book
2017-11-29 13:11:06 ERROR Serializer:24 - com.senla.entity.Order
2017-11-29 13:11:06 ERROR Serializer:24 - com.senla.entity.Reader
2017-11-29 13:11:06 ERROR Serializer:24 - com.senla.entity.Request
2017-11-29 13:18:56 ERROR Input:23 - For input string: "l"
2017-11-29 13:18:59 ERROR Input:23 - For input string: "o"
2017-12-03 09:16:03 ERROR Input:23 - For input string: "l"
2017-12-03 09:17:00 ERROR Input:23 - For input string: "l"
2017-12-03 09:17:52 ERROR Input:23 - For input string: "l"
2017-12-03 09:18:57 ERROR Input:23 - For input string: "l"
2017-12-03 09:21:34 ERROR Serializer:26 - data\boook.bin (The system cannot find the file specified)
2017-12-03 09:22:08 ERROR Serializer:26 - data\boook.bin (The system cannot find the file specified)
2017-12-03 09:22:13 ERROR Input:23 - For input string: ""
2017-12-03 11:05:49 ERROR Input:23 - For input string: "l"
2017-12-03 19:29:45 ERROR Parser:30 - Unparseable date: "06-08-01"
2017-12-03 19:29:45 ERROR Parser:30 - Unparseable date: "01-07-99"
2017-12-03 19:29:45 ERROR Parser:30 - Unparseable date: "16-03-98"
2017-12-03 19:29:45 ERROR Parser:30 - Unparseable date: "22-07-06"
2017-12-03 19:29:45 ERROR Parser:30 - Unparseable date: "19-04-87"
2017-12-03 19:38:03 ERROR Parser:30 - Unparseable date: "06-08-01"
2017-12-03 19:38:03 ERROR Parser:30 - Unparseable date: "01-07-99"
2017-12-03 19:38:03 ERROR Parser:30 - Unparseable date: "16-03-98"
2017-12-03 19:38:03 ERROR Parser:30 - Unparseable date: "22-07-06"
2017-12-03 19:38:03 ERROR Parser:30 - Unparseable date: "19-04-87"
2017-12-03 19:41:44 ERROR CSVWorker:28 - data\bean.csv (The process cannot access the file because it is being used by another process)
2017-12-03 20:30:44 ERROR Parser:30 - Unparseable date: "06/08/2001"
2017-12-03 20:31:21 ERROR Parser:30 - Unparseable date: "01/07/1999"
2017-12-03 20:31:21 ERROR Parser:30 - Unparseable date: "16/03/1998"
2017-12-03 20:31:21 ERROR Parser:30 - Unparseable date: "22/07/2006"
2017-12-03 20:31:21 ERROR Parser:30 - Unparseable date: "19/04/1987"
2017-12-03 20:33:10 ERROR Parser:30 - Unparseable date: "06-08-01"
2017-12-03 20:33:10 ERROR Parser:30 - Unparseable date: "01-07-99"
2017-12-03 20:33:10 ERROR Parser:30 - Unparseable date: "16-03-98"
2017-12-03 20:33:10 ERROR Parser:30 - Unparseable date: "22-07-06"
2017-12-03 20:33:10 ERROR Parser:30 - Unparseable date: "19-04-87"
2017-12-03 20:35:57 ERROR Parser:30 - Unparseable date: "01-07-99"
2017-12-03 20:35:57 ERROR Parser:30 - Unparseable date: "19-04-87"
2017-12-03 20:35:57 ERROR Parser:30 - Unparseable date: "16-03-98"
2017-12-03 20:35:57 ERROR Parser:30 - Unparseable date: "22-07-06"
2017-12-03 20:35:57 ERROR Parser:30 - Unparseable date: "06-08-01"
2017-12-03 20:36:57 ERROR Parser:30 - Unparseable date: "01-07-99"
2017-12-03 20:36:57 ERROR Parser:30 - Unparseable date: "19-04-87"
2017-12-03 20:36:57 ERROR Parser:30 - Unparseable date: "16-03-98"
2017-12-03 20:36:57 ERROR Parser:30 - Unparseable date: "22-07-06"
2017-12-03 20:36:57 ERROR Parser:30 - Unparseable date: "06-08-01"
2017-12-03 20:37:20 ERROR CSVWorker:28 - data\bean.csv (The process cannot access the file because it is being used by another process)
2017-12-03 20:37:53 ERROR Parser:30 - Unparseable date: "01-07-99"
2017-12-03 20:37:53 ERROR Parser:30 - Unparseable date: "19-04-87"
2017-12-03 20:37:53 ERROR Parser:30 - Unparseable date: "16-03-98"
2017-12-03 20:37:53 ERROR Parser:30 - Unparseable date: "22-07-06"
2017-12-03 20:37:53 ERROR Parser:30 - Unparseable date: "06-08-01"
2017-12-10 12:39:33 ERROR CSVWorker:40 - data\csv\book.csv (The process cannot access the file because it is being used by another process)
2017-12-10 12:39:54 ERROR CSVWorker:44 - Book
2017-12-10 12:47:37 ERROR Input:23 - For input string: ""
2017-12-10 12:53:45 ERROR CSVWorker:33 - data\csv\order.csv (The process cannot access the file because it is being used by another process)
2017-12-10 12:53:52 ERROR Input:23 - For input string: ""
2017-12-12 01:03:21 ERROR DependencyInjection:33 - Class com.senla.di.DependencyInjection can not access a member of class com.senla.dao.BookDao with modifiers "private"
2017-12-12 01:03:25 ERROR DependencyInjection:35 - Class com.senla.di.DependencyInjection can not access a member of class com.senla.dao.BookDao with modifiers "private"
2017-12-20 09:35:21 ERROR DependencyInjection:34 - Class com.senla.di.DependencyInjection can not access a member of class com.senla.dao.BookDao with modifiers "private"
2017-12-20 09:35:21 ERROR DependencyInjection:34 - Class com.senla.di.DependencyInjection can not access a member of class com.senla.dao.ReaderDao with modifiers "private"
2017-12-20 09:35:21 ERROR DependencyInjection:34 - Class com.senla.di.DependencyInjection can not access a member of class com.senla.dao.OrderDao with modifiers "private"
2017-12-20 09:35:21 ERROR DependencyInjection:34 - Class com.senla.di.DependencyInjection can not access a member of class com.senla.dao.mysql.RequestDao with modifiers "private"
2017-12-20 09:36:19 ERROR DependencyInjection:34 - Class com.senla.di.DependencyInjection can not access a member of class com.senla.dao.ReaderDao with modifiers "private"
2017-12-20 09:36:19 ERROR DependencyInjection:34 - Class com.senla.di.DependencyInjection can not access a member of class com.senla.dao.OrderDao with modifiers "private"
2017-12-20 09:36:19 ERROR DependencyInjection:34 - Class com.senla.di.DependencyInjection can not access a member of class com.senla.dao.mysql.RequestDao with modifiers "private"
2017-12-20 09:45:04 ERROR DependencyInjection:41 - Class com.senla.di.DependencyInjection can not access a member of class com.senla.dao.BookDao with modifiers "private"
2017-12-20 09:45:04 ERROR DependencyInjection:41 - Class com.senla.di.DependencyInjection can not access a member of class com.senla.dao.ReaderDao with modifiers "private"
2017-12-20 09:45:04 ERROR DependencyInjection:41 - Class com.senla.di.DependencyInjection can not access a member of class com.senla.dao.OrderDao with modifiers "private"
2017-12-20 09:45:04 ERROR DependencyInjection:41 - Class com.senla.di.DependencyInjection can not access a member of class com.senla.dao.mysql.RequestDao with modifiers "private"
2017-12-28 21:21:19 ERROR CSVWorker:154 - Book.<init>()
2017-12-28 21:22:31 ERROR CSVWorker:154 - Book.<init>()
2017-12-28 21:23:18 ERROR CSVWorker:154 - Book.<init>()
2017-12-28 21:29:10 ERROR CSVWorker:154 - Book.<init>()
2017-12-28 21:37:53 ERROR CSVWorker:154 - Book.<init>()
2017-12-28 21:38:27 ERROR CSVWorker:156 - Book.<init>()
2017-12-28 21:42:25 ERROR CSVWorker:156 - Book.<init>()
2017-12-28 21:42:52 ERROR CSVWorker:156 - Book.<init>()
2017-12-28 21:44:49 ERROR CSVWorker:156 - [Ljava.lang.StackTraceElement;@523884b2
2017-12-28 21:47:28 ERROR CSVWorker:155 - Book.<init>()
2017-12-28 21:50:05 ERROR CSVWorker:155 - Book.<init>()
2017-12-28 21:51:44 ERROR CSVWorker:156 - Book
2017-12-28 21:53:23 ERROR CSVWorker:156 - Book
2017-12-28 21:54:22 ERROR CSVWorker:156 - Can not set int field Book.price to java.lang.String
2017-12-28 21:57:18 ERROR CSVWorker:154 - Can not set int field Book.price to java.lang.String
2017-12-28 22:04:38 ERROR CSVWorker:152 - Can not set int field Book.price to java.lang.String
2017-12-28 22:05:08 ERROR CSVWorker:152 - Can not set int field Book.price to java.lang.String
2017-12-28 22:08:31 ERROR CSVWorker:152 - Can not set int field Book.price to java.lang.String
2017-12-28 22:09:51 ERROR CSVWorker:152 - java.lang.Integer.parseInteger(java.lang.String)
2017-12-28 22:10:19 ERROR CSVWorker:152 - java.lang.Integer.parseInteger(java.lang.String)
2017-12-28 22:24:30 ERROR CSVWorker:152 - java.lang.Integer.parseInteger(java.lang.String)
2017-12-28 22:25:24 ERROR CSVWorker:140 - For input string: "false"
2017-12-28 22:32:06 ERROR CSVWorker:144 - For input string: "false"
2017-12-28 22:33:17 ERROR CSVWorker:144 - For input string: "false"
2017-12-28 22:33:24 ERROR CSVWorker:145 - For input string: "false"
2017-12-28 22:39:02 ERROR CSVWorker:145 - For input string: "false"
2017-12-28 23:52:56 ERROR Parser:59 - For input string: "true"
2018-02-11 01:23:59 ERROR DaoFactory:39 - Database Connection Creation Failed: 
java.sql.SQLException: No suitable driver found for "jdbc:mysql://localhost:3306/book_shop?autoReconnect=true&useSSL=false";
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:703)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
	at com.senla.connector.DBConnector.<init>(DaoFactory.java:36)
	at com.senla.connector.DBConnector.getInstance(DaoFactory.java:17)
	at BookManager.<init>(BookManager.java:19)
	at Facade.<init>(OnlineBookStore.java:20)
	at Facade.getInstance(OnlineBookStore.java:29)
	at com.senla.main.Main.main(Main.java:14)
2018-02-11 01:23:59 ERROR DependencyInjection:36 - 
2018-02-11 01:33:59 ERROR DaoFactory:41 - Database Connection Creation Failed: 
java.sql.SQLException: No suitable driver found for "jdbc:mysql://localhost:3306/book_shop?autoReconnect=true&useSSL=false";
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:703)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
	at com.senla.connector.DBConnector.<init>(DaoFactory.java:38)
	at com.senla.connector.DBConnector.getInstance(DaoFactory.java:18)
	at BookManager.<init>(BookManager.java:19)
	at Facade.<init>(OnlineBookStore.java:20)
	at Facade.getInstance(OnlineBookStore.java:29)
	at com.senla.main.Main.main(Main.java:14)
2018-02-11 01:33:59 ERROR DependencyInjection:36 - 
2018-02-11 01:37:16 ERROR DaoFactory:41 - Database Connection Creation Failed: 
java.sql.SQLException: No suitable driver found for "jdbc:mysql://localhost:3306/book_shop?autoReconnect=true&useSSL=false";
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:703)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
	at com.senla.connector.DBConnector.<init>(DaoFactory.java:38)
	at com.senla.connector.DBConnector.getInstance(DaoFactory.java:18)
	at BookManager.<init>(BookManager.java:19)
	at Facade.<init>(OnlineBookStore.java:20)
	at Facade.getInstance(OnlineBookStore.java:29)
	at com.senla.main.Main.main(Main.java:14)
2018-02-11 01:37:16 ERROR DependencyInjection:36 - 
2018-02-11 01:40:02 ERROR DaoFactory:42 - Database Connection Creation Failed: 
java.sql.SQLException: No suitable driver found for "jdbc:mysql://localhost:3306/book_shop?autoReconnect=true&useSSL=false";
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:703)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
	at com.senla.connector.DBConnector.<init>(DaoFactory.java:39)
	at com.senla.connector.DBConnector.getInstance(DaoFactory.java:19)
	at BookManager.<init>(BookManager.java:19)
	at Facade.<init>(OnlineBookStore.java:20)
	at Facade.getInstance(OnlineBookStore.java:29)
	at com.senla.main.Main.main(Main.java:14)
2018-02-11 01:40:02 ERROR DependencyInjection:36 - 
2018-02-11 02:08:42 ERROR Executor:32 - Can't close statement
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1184)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1179)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2355)
	at com.senla.executor.Executor.execQuery(Executor.java:24)
	at BookManager.sortBooks(BookManager.java:54)
	at Facade.sortBooksBy(OnlineBookStore.java:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 09:37:14 ERROR Main:26 - Failed socket connection
java.net.BindException: Address already in use: NET_Bind
	at java.base/java.net.DualStackPlainSocketImpl.bind0(Native Method)
	at java.base/java.net.DualStackPlainSocketImpl.socketBind(DualStackPlainSocketImpl.java:106)
	at java.base/java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:437)
	at java.base/java.net.PlainSocketImpl.bind(PlainSocketImpl.java:174)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:381)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:243)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:135)
	at com.senla.main.Main.main(Main.java:17)
2018-02-11 09:37:34 ERROR Main:26 - Failed socket connection
java.net.BindException: Address already in use: NET_Bind
	at java.base/java.net.DualStackPlainSocketImpl.bind0(Native Method)
	at java.base/java.net.DualStackPlainSocketImpl.socketBind(DualStackPlainSocketImpl.java:106)
	at java.base/java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:437)
	at java.base/java.net.PlainSocketImpl.bind(PlainSocketImpl.java:174)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:381)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:243)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:135)
	at com.senla.main.Main.main(Main.java:17)
2018-02-11 09:42:36 TRACE Main:19 - Started, waiting for connection
2018-02-11 09:42:54 TRACE Main:18 - Started, waiting for connection
2018-02-11 09:43:13 ERROR Main:25 - Failed socket connection
java.net.BindException: Address already in use: NET_Bind
	at java.base/java.net.DualStackPlainSocketImpl.bind0(Native Method)
	at java.base/java.net.DualStackPlainSocketImpl.socketBind(DualStackPlainSocketImpl.java:106)
	at java.base/java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:437)
	at java.base/java.net.PlainSocketImpl.bind(PlainSocketImpl.java:174)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:381)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:243)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:135)
	at com.senla.main.Main.main(Main.java:17)
2018-02-11 09:43:28 TRACE Main:18 - Started, waiting for connection
2018-02-11 10:33:38 TRACE Main:18 - Started, waiting for connection
2018-02-11 12:28:23 TRACE Main:18 - Started, waiting for connection
2018-02-11 14:20:59 TRACE Main:18 - Started, waiting for connection
2018-02-11 14:21:13 ERROR Executor:29 - Can't close result
java.sql.SQLException: Column 'orderId' not found.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1080)
	at com.mysql.jdbc.ResultSetImpl.getInt(ResultSetImpl.java:2570)
	at com.senla.executor.handler.BookHandler.handle(BookHandler.java:33)
	at com.senla.executor.handler.BookHandler.handle(BookHandler.java:13)
	at com.senla.executor.Executor.execQuery(Executor.java:27)
	at BookManager.sortBooks(BookManager.java:60)
	at Facade.sortBooksBy(OnlineBookStore.java:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 14:21:46 ERROR OrderManager:79 - Can't close
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1184)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1179)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2355)
	at OrderManager.getAmountExecutedOrders(OrderManager.java:71)
	at Facade.getAmountExecutedOrders(OnlineBookStore.java:181)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:19)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 14:21:56 ERROR OrderManager:60 - Can't close
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1184)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1179)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2355)
	at OrderManager.getAllPrice(OrderManager.java:52)
	at Facade.getAllPrice(OnlineBookStore.java:176)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:19)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 14:22:03 ERROR Executor:32 - Can't close statement
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1184)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1179)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2355)
	at com.senla.executor.Executor.execQuery(Executor.java:24)
	at OrderManager.sortOrders(OrderManager.java:96)
	at Facade.sortOrdersBy(OnlineBookStore.java:73)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 14:22:34 TRACE Main:18 - Started, waiting for connection
2018-02-11 14:22:49 TRACE Main:18 - Started, waiting for connection
2018-02-11 14:23:43 TRACE Main:18 - Started, waiting for connection
2018-02-11 14:23:57 ERROR Executor:32 - Can't close statement
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1184)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1179)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2355)
	at com.senla.executor.Executor.execQuery(Executor.java:24)
	at BookManager.sortBooks(BookManager.java:60)
	at Facade.sortBooksBy(OnlineBookStore.java:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 14:24:16 TRACE Main:18 - Started, waiting for connection
2018-02-11 14:24:23 ERROR Executor:32 - Can't close statement
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1184)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1179)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2355)
	at com.senla.executor.Executor.execQuery(Executor.java:24)
	at BookManager.sortBooks(BookManager.java:60)
	at Facade.sortBooksBy(OnlineBookStore.java:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 14:24:48 TRACE Main:18 - Started, waiting for connection
2018-02-11 14:24:54 TRACE Main:18 - Started, waiting for connection
2018-02-11 14:25:44 TRACE Main:18 - Started, waiting for connection
2018-02-11 14:26:00 ERROR Executor:32 - Can't close statement
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1184)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1179)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2355)
	at com.senla.executor.Executor.execQuery(Executor.java:24)
	at BookManager.sortBooks(BookManager.java:60)
	at Facade.sortBooksBy(OnlineBookStore.java:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 14:26:39 ERROR Executor:32 - Can't close statement
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1184)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1179)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2355)
	at com.senla.executor.Executor.execQuery(Executor.java:24)
	at BookManager.sortBooks(BookManager.java:60)
	at Facade.sortBooksBy(OnlineBookStore.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 14:27:50 ERROR Executor:32 - Can't close statement
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1184)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1179)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2355)
	at com.senla.executor.Executor.execQuery(Executor.java:24)
	at BookManager.sortBooks(BookManager.java:60)
	at Facade.sortBooksBy(OnlineBookStore.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 14:30:05 TRACE Main:18 - Started, waiting for connection
2018-02-11 14:30:14 TRACE BookManager:57 - Open connection
2018-02-11 14:30:14 ERROR Executor:29 - Can't close result
java.sql.SQLException: Column 'orderId' not found.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1080)
	at com.mysql.jdbc.ResultSetImpl.getInt(ResultSetImpl.java:2570)
	at com.senla.executor.handler.BookHandler.handle(BookHandler.java:33)
	at com.senla.executor.handler.BookHandler.handle(BookHandler.java:13)
	at com.senla.executor.Executor.execQuery(Executor.java:27)
	at BookManager.sortBooks(BookManager.java:60)
	at Facade.sortBooksBy(OnlineBookStore.java:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 14:31:19 TRACE Main:18 - Started, waiting for connection
2018-02-11 14:31:37 TRACE BookManager:57 - Open connection
2018-02-11 14:31:37 ERROR Executor:32 - Can't close statement
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1184)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1179)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2355)
	at com.senla.executor.Executor.execQuery(Executor.java:24)
	at BookManager.sortBooks(BookManager.java:60)
	at Facade.sortBooksBy(OnlineBookStore.java:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 14:33:52 TRACE Main:18 - Started, waiting for connection
2018-02-11 14:33:52 ERROR Main:25 - Failed socket connection
java.net.SocketException: Connection reset by peer: socket write error
	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at java.base/java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1883)
	at java.base/java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(ObjectOutputStream.java:1792)
	at java.base/java.io.ObjectOutputStream.<init>(ObjectOutputStream.java:248)
	at com.senla.main.ServerThread.<init>(ServerThread.java:18)
	at com.senla.main.Main.main(Main.java:21)
2018-02-11 14:33:54 TRACE Main:18 - Started, waiting for connection
2018-02-11 14:34:23 ERROR Main:25 - Failed socket connection
java.net.BindException: Address already in use: NET_Bind
	at java.base/java.net.DualStackPlainSocketImpl.bind0(Native Method)
	at java.base/java.net.DualStackPlainSocketImpl.socketBind(DualStackPlainSocketImpl.java:106)
	at java.base/java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:437)
	at java.base/java.net.PlainSocketImpl.bind(PlainSocketImpl.java:174)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:381)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:243)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:135)
	at com.senla.main.Main.main(Main.java:17)
2018-02-11 14:34:27 TRACE Main:18 - Started, waiting for connection
2018-02-11 14:34:34 TRACE BookManager:57 - Open connection
2018-02-11 14:35:55 ERROR Executor:29 - Can't close result
java.sql.SQLException: Column 'orderId' not found.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1080)
	at com.mysql.jdbc.ResultSetImpl.getInt(ResultSetImpl.java:2570)
	at com.senla.executor.handler.BookHandler.handle(BookHandler.java:33)
	at com.senla.executor.handler.BookHandler.handle(BookHandler.java:13)
	at com.senla.executor.Executor.execQuery(Executor.java:27)
	at BookManager.sortBooks(BookManager.java:60)
	at Facade.sortBooksBy(OnlineBookStore.java:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 14:37:47 TRACE Main:18 - Started, waiting for connection
2018-02-11 14:37:55 TRACE BookManager:57 - Open connection
2018-02-11 14:37:55 ERROR Executor:29 - Can't close result
java.sql.SQLException: Column 'readerId' not found.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1080)
	at com.mysql.jdbc.ResultSetImpl.getInt(ResultSetImpl.java:2570)
	at com.senla.executor.handler.BookHandler.handle(BookHandler.java:42)
	at com.senla.executor.handler.BookHandler.handle(BookHandler.java:13)
	at com.senla.executor.Executor.execQuery(Executor.java:27)
	at BookManager.sortBooks(BookManager.java:60)
	at Facade.sortBooksBy(OnlineBookStore.java:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 14:45:01 TRACE Main:18 - Started, waiting for connection
2018-02-11 14:45:06 TRACE BookManager:57 - Open connection
2018-02-11 15:36:48 TRACE Main:18 - Started, waiting for connection
2018-02-11 15:37:23 TRACE OrderManager:93 - Open connection
2018-02-11 15:37:23 ERROR Executor:29 - Can't close result
java.sql.SQLException: Column 'name' not found.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1080)
	at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5177)
	at com.senla.executor.handler.OrderHandler.handle(OrderHandler.java:41)
	at com.senla.executor.handler.OrderHandler.handle(OrderHandler.java:14)
	at com.senla.executor.Executor.execQuery(Executor.java:27)
	at OrderManager.sortOrders(OrderManager.java:96)
	at Facade.sortOrdersBy(OnlineBookStore.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 15:42:58 TRACE Main:18 - Started, waiting for connection
2018-02-11 15:43:08 TRACE OrderManager:93 - Open connection
2018-02-11 15:43:08 ERROR Executor:29 - Can't close result
java.sql.SQLException: Column 'name' not found.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1080)
	at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5177)
	at com.senla.executor.handler.OrderHandler.handle(OrderHandler.java:41)
	at com.senla.executor.handler.OrderHandler.handle(OrderHandler.java:14)
	at com.senla.executor.Executor.execQuery(Executor.java:27)
	at OrderManager.sortOrders(OrderManager.java:96)
	at Facade.sortOrdersBy(OnlineBookStore.java:73)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 15:59:19 TRACE Main:18 - Started, waiting for connection
2018-02-11 15:59:29 TRACE OrderManager:93 - Open connection
2018-02-11 15:59:29 ERROR Executor:29 - Can't close result
java.sql.SQLException: Column 'name' not found.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1080)
	at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5177)
	at com.senla.executor.handler.OrderHandler.handle(OrderHandler.java:34)
	at com.senla.executor.handler.OrderHandler.handle(OrderHandler.java:15)
	at com.senla.executor.Executor.execQuery(Executor.java:27)
	at OrderManager.sortOrders(OrderManager.java:96)
	at Facade.sortOrdersBy(OnlineBookStore.java:73)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 16:00:46 TRACE Main:18 - Started, waiting for connection
2018-02-11 16:01:13 TRACE OrderManager:93 - Open connection
2018-02-11 16:01:47 TRACE Main:18 - Started, waiting for connection
2018-02-11 16:01:56 TRACE OrderManager:93 - Open connection
2018-02-11 16:02:10 TRACE Main:18 - Started, waiting for connection
2018-02-11 16:02:24 TRACE OrderManager:93 - Open connection
2018-02-11 16:05:39 TRACE Main:18 - Started, waiting for connection
2018-02-11 16:05:42 TRACE Main:18 - Started, waiting for connection
2018-02-11 16:05:51 TRACE OrderManager:93 - Open connection
2018-02-11 16:07:04 ERROR Executor:32 - Can't close statement
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'readerId' in 'from clause'
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2480)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2438)
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:845)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:745)
	at com.senla.executor.Executor.execQuery(Executor.java:25)
	at OrderManager.sortOrders(OrderManager.java:96)
	at Facade.sortOrdersBy(OnlineBookStore.java:73)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 16:07:07 TRACE Main:18 - Started, waiting for connection
2018-02-11 16:07:13 TRACE OrderManager:93 - Open connection
2018-02-11 16:07:24 TRACE Main:18 - Started, waiting for connection
2018-02-11 16:07:38 TRACE OrderManager:93 - Open connection
2018-02-11 16:10:26 TRACE Main:18 - Started, waiting for connection
2018-02-11 16:10:30 TRACE OrderManager:93 - Open connection
2018-02-11 16:10:59 TRACE Main:18 - Started, waiting for connection
2018-02-11 16:11:04 TRACE OrderManager:93 - Open connection
2018-02-11 16:12:17 TRACE Main:18 - Started, waiting for connection
2018-02-11 16:12:22 TRACE OrderManager:93 - Open connection
2018-02-11 16:18:51 TRACE Main:18 - Started, waiting for connection
2018-02-11 16:18:57 TRACE OrderManager:93 - Open connection
2018-02-11 16:18:57 ERROR Executor:29 - Can't close result
java.sql.SQLException: Conversion not supported for type com.senla.enums.Status
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ResultSetImpl.getObject(ResultSetImpl.java:4648)
	at com.mysql.jdbc.JDBC4ResultSet.getObject(JDBC4ResultSet.java:531)
	at com.mysql.jdbc.JDBC42ResultSet.getObject(JDBC42ResultSet.java:91)
	at com.mysql.jdbc.ResultSetImpl.getObject(ResultSetImpl.java:4655)
	at com.senla.executor.handler.OrderHandler.handle(OrderHandler.java:40)
	at com.senla.executor.handler.OrderHandler.handle(OrderHandler.java:15)
	at com.senla.executor.Executor.execQuery(Executor.java:27)
	at OrderManager.sortOrders(OrderManager.java:96)
	at Facade.sortOrdersBy(OnlineBookStore.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 16:19:54 TRACE Main:18 - Started, waiting for connection
2018-02-11 16:20:07 TRACE OrderManager:93 - Open connection
2018-02-11 16:20:22 TRACE BookManager:57 - Open connection
2018-02-11 16:20:22 ERROR Executor:32 - Can't close statement
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1184)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1179)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2355)
	at com.senla.executor.Executor.execQuery(Executor.java:24)
	at BookManager.sortBooks(BookManager.java:60)
	at Facade.sortBooksBy(OnlineBookStore.java:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 16:21:21 TRACE Main:18 - Started, waiting for connection
2018-02-11 16:21:28 TRACE OrderManager:93 - Open connection
2018-02-11 16:24:53 TRACE Main:18 - Started, waiting for connection
2018-02-11 16:25:00 TRACE BookManager:57 - Open connection
2018-02-11 16:30:42 TRACE Main:18 - Started, waiting for connection
2018-02-11 16:31:12 TRACE BookManager:57 - Open connection
2018-02-11 16:32:04 TRACE Main:18 - Started, waiting for connection
2018-02-11 16:32:16 TRACE OrderManager:93 - Open connection
2018-02-11 16:32:22 TRACE BookManager:57 - Open connection
2018-02-11 16:32:22 ERROR Executor:32 - Can't close statement
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1184)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1179)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2355)
	at com.senla.executor.Executor.execQuery(Executor.java:24)
	at BookManager.sortBooks(BookManager.java:60)
	at Facade.sortBooksBy(OnlineBookStore.java:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 16:32:29 TRACE Main:18 - Started, waiting for connection
2018-02-11 16:32:36 TRACE BookManager:57 - Open connection
2018-02-11 16:32:41 TRACE BookManager:57 - Open connection
2018-02-11 16:32:41 ERROR Executor:32 - Can't close statement
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1184)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1179)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2355)
	at com.senla.executor.Executor.execQuery(Executor.java:24)
	at BookManager.sortBooks(BookManager.java:60)
	at Facade.sortBooksBy(OnlineBookStore.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 16:34:10 TRACE Main:18 - Started, waiting for connection
2018-02-11 16:34:19 TRACE BookManager:57 - Open connection
2018-02-11 16:35:00 TRACE Main:18 - Started, waiting for connection
2018-02-11 16:35:00 ERROR Main:25 - Failed socket connection
java.net.SocketException: Connection reset by peer: socket write error
	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at java.base/java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1883)
	at java.base/java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(ObjectOutputStream.java:1792)
	at java.base/java.io.ObjectOutputStream.<init>(ObjectOutputStream.java:248)
	at com.senla.main.ServerThread.<init>(ServerThread.java:18)
	at com.senla.main.Main.main(Main.java:21)
2018-02-11 16:35:06 TRACE Main:18 - Started, waiting for connection
2018-02-11 16:35:08 TRACE Main:18 - Started, waiting for connection
2018-02-11 16:35:13 TRACE BookManager:57 - Open connection
2018-02-11 16:36:33 ERROR Main:25 - Failed socket connection
java.net.BindException: Address already in use: NET_Bind
	at java.base/java.net.DualStackPlainSocketImpl.bind0(Native Method)
	at java.base/java.net.DualStackPlainSocketImpl.socketBind(DualStackPlainSocketImpl.java:106)
	at java.base/java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:437)
	at java.base/java.net.PlainSocketImpl.bind(PlainSocketImpl.java:174)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:381)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:243)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:135)
	at com.senla.main.Main.main(Main.java:17)
2018-02-11 16:36:37 TRACE Main:18 - Started, waiting for connection
2018-02-11 16:36:57 TRACE Main:18 - Started, waiting for connection
2018-02-11 16:37:06 TRACE BookManager:57 - Open connection
2018-02-11 16:39:02 TRACE Main:18 - Started, waiting for connection
2018-02-11 16:39:09 TRACE BookManager:57 - Open connection
2018-02-11 16:39:13 TRACE BookManager:57 - Open connection
2018-02-11 16:39:13 ERROR Executor:32 - Can't close statement
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1184)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1179)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2355)
	at com.senla.executor.Executor.execQuery(Executor.java:24)
	at BookManager.sortBooks(BookManager.java:60)
	at Facade.sortBooksBy(OnlineBookStore.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 16:39:20 TRACE Main:18 - Started, waiting for connection
2018-02-11 16:39:26 TRACE BookManager:57 - Open connection
2018-02-11 16:39:29 TRACE BookManager:57 - Open connection
2018-02-11 16:39:29 ERROR Executor:32 - Can't close statement
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1184)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1179)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2355)
	at com.senla.executor.Executor.execQuery(Executor.java:24)
	at BookManager.sortBooks(BookManager.java:60)
	at Facade.sortBooksBy(OnlineBookStore.java:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 16:39:49 TRACE OrderManager:93 - Open connection
2018-02-11 16:39:49 ERROR Executor:32 - Can't close statement
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1184)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1179)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2355)
	at com.senla.executor.Executor.execQuery(Executor.java:24)
	at OrderManager.sortOrders(OrderManager.java:96)
	at Facade.sortOrdersBy(OnlineBookStore.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 16:40:04 TRACE Main:18 - Started, waiting for connection
2018-02-11 16:40:09 TRACE BookManager:57 - Open connection
2018-02-11 16:40:11 TRACE BookManager:57 - Open connection
2018-02-11 16:40:11 ERROR Executor:32 - Can't close statement
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1184)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1179)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2355)
	at com.senla.executor.Executor.execQuery(Executor.java:24)
	at BookManager.sortBooks(BookManager.java:60)
	at Facade.sortBooksBy(OnlineBookStore.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 16:45:22 TRACE Main:18 - Started, waiting for connection
2018-02-11 16:45:29 TRACE BookManager:57 - Open connection
2018-02-11 16:45:31 TRACE BookManager:57 - Open connection
2018-02-11 16:45:34 TRACE BookManager:57 - Open connection
2018-02-11 16:45:37 TRACE BookManager:57 - Open connection
2018-02-11 16:45:46 TRACE OrderManager:93 - Open connection
2018-02-11 16:45:46 ERROR Executor:32 - Can't close statement
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1184)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1179)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2355)
	at com.senla.executor.Executor.execQuery(Executor.java:24)
	at OrderManager.sortOrders(OrderManager.java:96)
	at Facade.sortOrdersBy(OnlineBookStore.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 16:49:02 TRACE Main:18 - Started, waiting for connection
2018-02-11 16:49:08 TRACE BookManager:57 - Open connection
2018-02-11 16:49:09 TRACE BookManager:57 - Open connection
2018-02-11 16:49:09 ERROR Executor:32 - Can't close statement
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1184)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1179)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2355)
	at com.senla.executor.Executor.execQuery(Executor.java:24)
	at BookManager.sortBooks(BookManager.java:60)
	at Facade.sortBooksBy(OnlineBookStore.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 16:50:47 TRACE Main:18 - Started, waiting for connection
2018-02-11 16:50:55 TRACE BookManager:56 - Open connection
2018-02-11 16:50:57 TRACE BookManager:56 - Open connection
2018-02-11 16:50:59 TRACE BookManager:56 - Open connection
2018-02-11 16:51:01 TRACE BookManager:56 - Open connection
2018-02-11 16:51:33 ERROR OrderManager:78 - Can't close
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AS count FROM book_order WHERE status = CANCELED' at line 1
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2480)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2438)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1381)
	at OrderManager.getAmountExecutedOrders(OrderManager.java:71)
	at Facade.getAmountExecutedOrders(OnlineBookStore.java:181)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:19)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 16:51:40 TRACE OrderManager:92 - Open connection
2018-02-11 16:55:52 TRACE Main:18 - Started, waiting for connection
2018-02-11 16:55:59 TRACE OrderManager:92 - Open connection
2018-02-11 16:59:46 TRACE Main:18 - Started, waiting for connection
2018-02-11 16:59:49 TRACE OrderManager:92 - Open connection
2018-02-11 19:56:22 TRACE Main:18 - Started, waiting for connection
2018-02-11 19:56:26 TRACE Main:18 - Started, waiting for connection
2018-02-11 19:56:36 TRACE BookManager:56 - Open connection
2018-02-11 19:56:46 TRACE Main:18 - Started, waiting for connection
2018-02-11 19:56:52 TRACE BookManager:56 - Open connection
2018-02-11 19:56:53 TRACE BookManager:56 - Open connection
2018-02-11 19:56:54 TRACE BookManager:56 - Open connection
2018-02-11 19:57:01 TRACE BookManager:56 - Open connection
2018-02-11 19:57:04 TRACE BookManager:56 - Open connection
2018-02-11 19:57:52 TRACE BookManager:56 - Open connection
2018-02-11 19:58:17 TRACE OrderManager:92 - Open connection
2018-02-11 19:58:28 TRACE OrderManager:92 - Open connection
2018-02-11 19:58:29 TRACE OrderManager:92 - Open connection
2018-02-11 19:58:30 TRACE OrderManager:92 - Open connection
2018-02-11 20:00:13 TRACE OrderManager:92 - Open connection
2018-02-11 20:00:13 ERROR Executor:32 - Can't close statement
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'CANCELED' in 'where clause'
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2480)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2438)
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:845)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:745)
	at com.senla.executor.Executor.execQuery(Executor.java:25)
	at OrderManager.sortOrders(OrderManager.java:95)
	at Facade.sortExecutedOrdersBy(OnlineBookStore.java:88)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 20:00:24 TRACE OrderManager:92 - Open connection
2018-02-11 20:00:24 ERROR Executor:32 - Can't close statement
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'CANCELED' in 'where clause'
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2480)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2438)
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:845)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:745)
	at com.senla.executor.Executor.execQuery(Executor.java:25)
	at OrderManager.sortOrders(OrderManager.java:95)
	at Facade.sortExecutedOrdersBy(OnlineBookStore.java:90)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 20:02:32 TRACE OrderManager:92 - Open connection
2018-02-11 20:02:56 TRACE OrderManager:92 - Open connection
2018-02-11 20:06:33 TRACE Main:18 - Started, waiting for connection
2018-02-11 20:06:44 TRACE OrderManager:92 - Open connection
2018-02-11 20:06:56 TRACE OrderManager:92 - Open connection
2018-02-11 20:07:27 TRACE OrderManager:92 - Open connection
2018-02-11 20:07:27 ERROR Executor:32 - Can't close statement
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'EXECUTED' in 'where clause'
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2480)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2438)
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:845)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:745)
	at com.senla.executor.Executor.execQuery(Executor.java:25)
	at OrderManager.sortOrders(OrderManager.java:95)
	at Facade.sortExecutedOrdersBy(OnlineBookStore.java:90)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 20:10:09 TRACE Main:18 - Started, waiting for connection
2018-02-11 20:10:14 TRACE OrderManager:92 - Open connection
2018-02-11 20:10:21 TRACE OrderManager:92 - Open connection
2018-02-11 20:13:57 TRACE Main:18 - Started, waiting for connection
2018-02-11 20:14:04 TRACE OrderManager:92 - Open connection
2018-02-11 20:14:36 TRACE OrderManager:92 - Open connection
2018-02-11 20:14:42 TRACE OrderManager:92 - Open connection
2018-02-11 20:14:46 TRACE OrderManager:92 - Open connection
2018-02-11 20:15:24 TRACE OrderManager:92 - Open connection
2018-02-11 20:15:58 TRACE OrderManager:92 - Open connection
2018-02-11 20:16:26 TRACE OrderManager:92 - Open connection
2018-02-11 20:17:08 TRACE OrderManager:92 - Open connection
2018-02-11 20:17:36 TRACE OrderManager:92 - Open connection
2018-02-11 20:18:50 TRACE OrderManager:92 - Open connection
2018-02-11 20:19:15 TRACE OrderManager:92 - Open connection
2018-02-11 20:22:39 TRACE Main:18 - Started, waiting for connection
2018-02-11 20:22:59 TRACE OrderManager:92 - Open connection
2018-02-11 20:23:31 TRACE Main:18 - Started, waiting for connection
2018-02-11 20:23:43 TRACE OrderManager:92 - Open connection
2018-02-11 20:29:52 TRACE Main:18 - Started, waiting for connection
2018-02-11 20:29:57 TRACE OrderManager:92 - Open connection
2018-02-11 20:30:00 TRACE OrderManager:92 - Open connection
2018-02-11 20:31:20 TRACE BookManager:56 - Open connection
2018-02-11 20:35:26 TRACE Main:18 - Started, waiting for connection
2018-02-11 20:35:41 TRACE BookManager:56 - Open connection
2018-02-11 20:35:41 ERROR Executor:29 - Can't close result
java.sql.SQLException: Column 'readerId' not found.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1080)
	at com.mysql.jdbc.ResultSetImpl.getInt(ResultSetImpl.java:2570)
	at com.senla.executor.handler.BookHandler.handle(BookHandler.java:42)
	at com.senla.executor.handler.BookHandler.handle(BookHandler.java:13)
	at com.senla.executor.Executor.execQuery(Executor.java:27)
	at BookManager.sortBooks(BookManager.java:59)
	at Facade.sortBooksBy(OnlineBookStore.java:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 20:59:08 TRACE Main:18 - Started, waiting for connection
2018-02-11 20:59:28 TRACE BookManager:56 - Open connection
2018-02-11 20:59:34 TRACE BookManager:56 - Open connection
2018-02-11 20:59:43 TRACE BookManager:56 - Open connection
2018-02-11 20:59:43 ERROR Executor:32 - Can't close statement
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ORDER BY title' at line 1
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2480)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2438)
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:845)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:745)
	at com.senla.executor.Executor.execQuery(Executor.java:25)
	at BookManager.sortBooks(BookManager.java:59)
	at Facade.sortRequestsBy(OnlineBookStore.java:102)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:28)
2018-02-11 20:59:43 ERROR ServerThread:32 - ServerThread stream is failed
java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:224)
	at java.base/java.io.ObjectInputStream$PeekInputStream.peek(ObjectInputStream.java:2714)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peek(ObjectInputStream.java:3041)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:3051)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1552)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 21:00:18 TRACE Main:18 - Started, waiting for connection
2018-02-11 21:00:24 TRACE BookManager:56 - Open connection
2018-02-11 21:00:31 ERROR ServerThread:32 - ServerThread stream is failed
java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:224)
	at java.base/java.io.ObjectInputStream$PeekInputStream.peek(ObjectInputStream.java:2714)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peek(ObjectInputStream.java:3041)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:3051)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1552)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-12 15:36:52 TRACE Main:18 - Started, waiting for connection
2018-02-12 15:37:04 ERROR OrderManager:78 - Can't close
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AS count FROM book_order WHERE status = CANCELED' at line 1
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2480)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2438)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1381)
	at OrderManager.getAmountExecutedOrders(OrderManager.java:71)
	at Facade.getAmountExecutedOrders(OnlineBookStore.java:180)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:19)
	at com.senla.main.ServerThread.run(ServerThread.java:28)
2018-02-12 15:37:16 ERROR ServerThread:32 - ServerThread stream is failed
java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:224)
	at java.base/java.io.ObjectInputStream$PeekInputStream.peek(ObjectInputStream.java:2714)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peek(ObjectInputStream.java:3041)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:3051)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1552)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-12 15:54:09 TRACE Main:18 - Started, waiting for connection
2018-02-12 15:54:24 ERROR OrderManager:77 - Can't close
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AS count FROM book_order WHERE status = CANCELED' at line 1
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2480)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2438)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1381)
	at OrderManager.getAmountExecutedOrders(OrderManager.java:70)
	at Facade.getAmountExecutedOrders(OnlineBookStore.java:180)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:19)
	at com.senla.main.ServerThread.run(ServerThread.java:28)
2018-02-12 15:54:27 ERROR ServerThread:32 - ServerThread stream is failed
java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:224)
	at java.base/java.io.ObjectInputStream$PeekInputStream.peek(ObjectInputStream.java:2714)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peek(ObjectInputStream.java:3041)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:3051)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1552)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-12 15:56:42 TRACE Main:18 - Started, waiting for connection
2018-02-12 15:56:50 ERROR OrderManager:77 - Can't close
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AS count FROM book_order WHERE status = 'CANCELED'' at line 1
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2480)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2438)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1381)
	at OrderManager.getAmountExecutedOrders(OrderManager.java:70)
	at Facade.getAmountExecutedOrders(OnlineBookStore.java:180)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:19)
	at com.senla.main.ServerThread.run(ServerThread.java:28)
2018-02-12 15:56:53 ERROR ServerThread:32 - ServerThread stream is failed
java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:224)
	at java.base/java.io.ObjectInputStream$PeekInputStream.peek(ObjectInputStream.java:2714)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peek(ObjectInputStream.java:3041)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:3051)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1552)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-12 15:58:50 TRACE Main:18 - Started, waiting for connection
2018-02-12 15:58:57 ERROR ServerThread:32 - ServerThread stream is failed
java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:224)
	at java.base/java.io.ObjectInputStream$PeekInputStream.peek(ObjectInputStream.java:2714)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peek(ObjectInputStream.java:3041)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:3051)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1552)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-12 16:01:08 TRACE Main:18 - Started, waiting for connection
2018-02-12 16:01:19 ERROR ServerThread:32 - ServerThread stream is failed
java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:224)
	at java.base/java.io.ObjectInputStream$PeekInputStream.peek(ObjectInputStream.java:2714)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peek(ObjectInputStream.java:3041)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:3051)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1552)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-12 16:43:39 TRACE Main:18 - Started, waiting for connection
2018-02-12 16:43:50 TRACE BookManager:56 - Open connection
2018-02-12 16:43:59 TRACE BookManager:56 - Open connection
2018-02-12 16:44:35 TRACE BookManager:56 - Open connection
2018-02-12 16:44:42 TRACE BookManager:56 - Open connection
2018-02-12 16:45:19 ERROR ServerThread:32 - ServerThread stream is failed
java.lang.NoSuchMethodException: Facade.getOrder(java.lang.Integer)
	at java.base/java.lang.Class.getMethod(Class.java:2065)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:21)
	at com.senla.main.ServerThread.run(ServerThread.java:28)
2018-02-12 16:45:51 ERROR ServerThread:32 - ServerThread stream is failed
java.lang.NoSuchMethodException: Facade.getBook(java.lang.Integer)
	at java.base/java.lang.Class.getMethod(Class.java:2065)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:21)
	at com.senla.main.ServerThread.run(ServerThread.java:28)
2018-02-12 16:46:10 TRACE Main:18 - Started, waiting for connection
2018-02-12 16:54:12 ERROR ServerThread:32 - ServerThread stream is failed
java.lang.NoSuchMethodException: Facade.getBook(java.lang.Integer)
	at java.base/java.lang.Class.getMethod(Class.java:2065)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:21)
	at com.senla.main.ServerThread.run(ServerThread.java:28)
2018-02-12 16:54:44 TRACE Main:18 - Started, waiting for connection
2018-02-12 16:54:52 TRACE BookDao:73 - Open connection
2018-02-12 16:55:08 TRACE OrderDao:47 - Open connection
2018-02-12 16:55:08 ERROR Executor:29 - Can't close resultSet
java.sql.SQLException: Column 'orderId' not found.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1080)
	at com.mysql.jdbc.ResultSetImpl.getInt(ResultSetImpl.java:2570)
	at com.senla.executor.handler.OrderHandler.handle(OrderHandler.java:20)
	at com.senla.executor.handler.OrderHandler.handle(OrderHandler.java:14)
	at com.senla.executor.Executor.execQuery(Executor.java:27)
	at com.senla.dao.OrderDao.findById(OrderDao.java:50)
	at OrderManager.findById(OrderManager.java:83)
	at Facade.getOrder(OnlineBookStore.java:165)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:28)
2018-02-12 16:55:08 ERROR ServerThread:32 - ServerThread stream is failed
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:28)
Caused by: java.lang.NullPointerException
	at com.senla.dao.OrderDao.findById(OrderDao.java:50)
	at OrderManager.findById(OrderManager.java:83)
	at Facade.getOrder(OnlineBookStore.java:165)
	... 6 more
2018-02-12 16:57:23 TRACE Main:18 - Started, waiting for connection
2018-02-12 16:57:29 TRACE BookDao:73 - Open connection
2018-02-12 16:57:37 TRACE OrderDao:47 - Open connection
2018-02-12 16:57:37 ERROR Executor:32 - Can't close statement
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'orderId' in 'where clause'
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2480)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2438)
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:845)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:745)
	at com.senla.executor.Executor.execQuery(Executor.java:25)
	at com.senla.dao.OrderDao.findById(OrderDao.java:50)
	at OrderManager.findById(OrderManager.java:83)
	at Facade.getOrder(OnlineBookStore.java:165)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:28)
2018-02-12 16:57:37 ERROR ServerThread:32 - ServerThread stream is failed
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:28)
Caused by: java.lang.NullPointerException
	at com.senla.dao.OrderDao.findById(OrderDao.java:50)
	at OrderManager.findById(OrderManager.java:83)
	at Facade.getOrder(OnlineBookStore.java:165)
	... 6 more
2018-02-12 16:59:26 TRACE Main:18 - Started, waiting for connection
2018-02-12 16:59:30 TRACE OrderDao:47 - Open connection
2018-02-12 16:59:31 ERROR Executor:29 - Can't close resultSet
java.sql.SQLException: Column 'name' not found.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1080)
	at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5177)
	at com.senla.executor.handler.OrderHandler.handle(OrderHandler.java:22)
	at com.senla.executor.handler.OrderHandler.handle(OrderHandler.java:14)
	at com.senla.executor.Executor.execQuery(Executor.java:27)
	at com.senla.dao.OrderDao.findById(OrderDao.java:50)
	at OrderManager.findById(OrderManager.java:83)
	at Facade.getOrder(OnlineBookStore.java:165)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:28)
2018-02-12 16:59:31 ERROR ServerThread:32 - ServerThread stream is failed
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:28)
Caused by: java.lang.NullPointerException
	at com.senla.dao.OrderDao.findById(OrderDao.java:50)
	at OrderManager.findById(OrderManager.java:83)
	at Facade.getOrder(OnlineBookStore.java:165)
	... 6 more
2018-02-12 17:03:24 TRACE Main:18 - Started, waiting for connection
2018-02-12 17:03:35 TRACE OrderDao:47 - Open connection
2018-02-12 17:03:51 TRACE OrderManager:90 - Open connection
2018-02-12 17:04:00 TRACE OrderManager:90 - Open connection
2018-02-12 17:04:04 TRACE OrderManager:90 - Open connection
2018-02-12 17:04:11 TRACE BookManager:56 - Open connection
2018-02-12 17:04:19 ERROR ServerThread:32 - ServerThread stream is failed
java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:224)
	at java.base/java.io.ObjectInputStream$PeekInputStream.peek(ObjectInputStream.java:2714)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peek(ObjectInputStream.java:3041)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:3051)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1552)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-12 19:12:48 TRACE Main:18 - Started, waiting for connection
2018-02-12 20:08:56 TRACE Main:18 - Started, waiting for connection
2018-02-12 20:12:54 TRACE Main:18 - Started, waiting for connection
2018-02-12 20:13:09 TRACE OrderManager:101 - Open connection
2018-02-12 20:13:45 TRACE OrderManager:101 - Open connection
2018-02-16 16:50:18 TRACE Main:18 - Started, waiting for connection
2018-02-16 16:51:33 TRACE Main:18 - Started, waiting for connection
2018-02-16 16:51:58 ERROR DependencyInjection:55 - com.senla.dao.BookDao.<init>(java.sql.Connection)
2018-02-16 16:51:58 ERROR DependencyInjection:55 - com.senla.dao.ReaderDao.<init>(java.sql.Connection)
2018-02-16 16:51:58 ERROR DependencyInjection:55 - com.senla.dao.OrderDao.<init>(java.sql.Connection)
2018-02-16 16:51:58 ERROR ServerThread:32 - ServerThread stream is failed
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:28)
Caused by: java.lang.NullPointerException
	at BookManager.getAll(BookManager.java:37)
	at Facade.sortBooksBy(OnlineBookStore.java:41)
	... 6 more
2018-02-16 16:53:22 TRACE Main:18 - Started, waiting for connection
2018-02-16 16:53:32 ERROR DependencyInjection:55 - com.senla.dao.BookDao.<init>(java.sql.Connection)
2018-02-16 16:53:32 ERROR DependencyInjection:55 - com.senla.dao.ReaderDao.<init>(java.sql.Connection)
2018-02-16 16:53:32 ERROR DependencyInjection:55 - com.senla.dao.OrderDao.<init>(java.sql.Connection)
2018-02-16 16:54:08 ERROR ServerThread:32 - ServerThread stream is failed
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:28)
Caused by: java.lang.NullPointerException
	at BookManager.getAll(BookManager.java:37)
	at Facade.sortBooksBy(OnlineBookStore.java:41)
	... 6 more
2018-02-16 16:54:54 TRACE Main:18 - Started, waiting for connection
2018-02-16 16:56:30 TRACE Main:18 - Started, waiting for connection
2018-02-16 16:57:33 ERROR DependencyInjection:55 - com.senla.dao.BookDao.<init>(java.sql.Connection)
2018-02-16 17:01:33 ERROR DependencyInjection:55 - com.senla.dao.ReaderDao.<init>(java.sql.Connection)
2018-02-16 17:01:33 ERROR DependencyInjection:55 - com.senla.dao.OrderDao.<init>(java.sql.Connection)
2018-02-16 17:01:33 ERROR ServerThread:32 - ServerThread stream is failed
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:28)
Caused by: java.lang.NullPointerException
	at BookManager.getAll(BookManager.java:37)
	at Facade.sortBooksBy(OnlineBookStore.java:41)
	... 6 more
2018-02-16 17:01:37 TRACE Main:18 - Started, waiting for connection
2018-02-16 17:01:43 ERROR DependencyInjection:55 - com.senla.dao.BookDao.<init>(java.sql.Connection)
2018-02-16 17:01:43 ERROR DependencyInjection:55 - com.senla.dao.ReaderDao.<init>(java.sql.Connection)
2018-02-16 17:01:43 ERROR DependencyInjection:55 - com.senla.dao.OrderDao.<init>(java.sql.Connection)
2018-02-16 17:01:43 ERROR ServerThread:32 - ServerThread stream is failed
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:28)
Caused by: java.lang.NullPointerException
	at BookManager.getAll(BookManager.java:37)
	at Facade.sortBooksBy(OnlineBookStore.java:41)
	... 6 more
2018-02-16 17:01:51 TRACE Main:18 - Started, waiting for connection
2018-02-16 17:04:04 ERROR DependencyInjection:55 - com.senla.dao.BookDao.<init>(java.sql.Connection)
2018-02-16 17:04:04 ERROR DependencyInjection:55 - com.senla.dao.ReaderDao.<init>(java.sql.Connection)
2018-02-16 17:04:04 ERROR DependencyInjection:55 - com.senla.dao.OrderDao.<init>(java.sql.Connection)
2018-02-16 17:04:04 ERROR ServerThread:32 - ServerThread stream is failed
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:28)
Caused by: java.lang.NullPointerException
	at BookManager.getAll(BookManager.java:37)
	at Facade.sortBooksBy(OnlineBookStore.java:41)
	... 6 more
2018-02-16 17:04:06 TRACE Main:18 - Started, waiting for connection
2018-02-16 17:07:18 ERROR DependencyInjection:55 - com.senla.dao.BookDao.<init>(java.sql.Connection)
2018-02-16 17:07:18 ERROR DependencyInjection:55 - com.senla.dao.ReaderDao.<init>(java.sql.Connection)
2018-02-16 17:07:18 ERROR DependencyInjection:55 - com.senla.dao.OrderDao.<init>(java.sql.Connection)
2018-02-16 17:07:18 ERROR ServerThread:32 - ServerThread stream is failed
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:28)
Caused by: java.lang.NullPointerException
	at BookManager.getAll(BookManager.java:37)
	at Facade.sortBooksBy(OnlineBookStore.java:41)
	... 6 more
2018-02-16 17:10:40 TRACE Main:18 - Started, waiting for connection
2018-02-16 17:12:08 ERROR Executor:54 - Can't close resultSet
java.sql.SQLException: Column 'isTheBookInStore' not found.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1080)
	at com.mysql.jdbc.ResultSetImpl.getBoolean(ResultSetImpl.java:1634)
	at com.senla.executor.handler.BookHandler.handle(BookHandler.java:21)
	at com.senla.executor.handler.BookHandler.handle(BookHandler.java:12)
	at com.senla.executor.Executor.execQuery(Executor.java:51)
	at com.senla.dao.GenericDao.getAll(ADao.java:80)
	at BookManager.getAll(BookManager.java:36)
	at Facade.sortBooksBy(OnlineBookStore.java:41)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:28)
2018-02-16 17:12:32 ERROR ServerThread:32 - ServerThread stream is failed
java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:224)
	at java.base/java.io.ObjectInputStream$PeekInputStream.peek(ObjectInputStream.java:2714)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peek(ObjectInputStream.java:3041)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:3051)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1552)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-16 17:13:30 TRACE Main:18 - Started, waiting for connection
2018-02-16 17:16:12 ERROR Executor:54 - Can't close resultSet
java.sql.SQLException: Column 'isTheBookInStore' not found.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1080)
	at com.mysql.jdbc.ResultSetImpl.getBoolean(ResultSetImpl.java:1634)
	at com.senla.executor.handler.BookHandler.handle(BookHandler.java:21)
	at com.senla.executor.handler.BookHandler.handle(BookHandler.java:12)
	at com.senla.executor.Executor.execQuery(Executor.java:51)
	at com.senla.dao.GenericDao.getAll(ADao.java:80)
	at BookManager.getAll(BookManager.java:36)
	at Facade.sortBooksBy(OnlineBookStore.java:41)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:28)
2018-02-16 17:16:14 TRACE Main:18 - Started, waiting for connection
2018-02-16 17:16:48 ERROR Executor:54 - Can't close resultSet
java.sql.SQLException: Column 'isTheBookInStore' not found.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1080)
	at com.mysql.jdbc.ResultSetImpl.getBoolean(ResultSetImpl.java:1634)
	at com.senla.executor.handler.BookHandler.handle(BookHandler.java:21)
	at com.senla.executor.handler.BookHandler.handle(BookHandler.java:12)
	at com.senla.executor.Executor.execQuery(Executor.java:51)
	at com.senla.dao.GenericDao.getAll(ADao.java:80)
	at BookManager.getAll(BookManager.java:36)
	at Facade.sortBooksBy(OnlineBookStore.java:41)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:28)
2018-02-16 17:17:10 TRACE Main:18 - Started, waiting for connection
2018-02-16 17:17:40 TRACE Main:18 - Started, waiting for connection
2018-02-16 17:18:45 ERROR ServerThread:32 - ServerThread stream is failed
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:28)
Caused by: java.lang.ClassCastException: java.base/java.util.ArrayList cannot be cast to Book
	at BookManager.getById(BookManager.java:31)
	at BookManager.getById(BookManager.java:11)
	at Facade.getBook(OnlineBookStore.java:142)
	... 6 more
2018-02-16 17:19:48 TRACE Main:18 - Started, waiting for connection
2018-02-16 17:21:08 ERROR ServerThread:32 - ServerThread stream is failed
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:28)
Caused by: java.lang.ClassCastException: java.base/java.util.ArrayList cannot be cast to Book
	at BookManager.getById(BookManager.java:31)
	at BookManager.getById(BookManager.java:11)
	at Facade.getBook(OnlineBookStore.java:142)
	... 6 more
2018-02-16 17:26:15 TRACE Main:18 - Started, waiting for connection
2018-02-16 17:27:01 ERROR Main:25 - Failed socket connection
java.net.BindException: Address already in use: NET_Bind
	at java.base/java.net.DualStackPlainSocketImpl.bind0(Native Method)
	at java.base/java.net.DualStackPlainSocketImpl.socketBind(DualStackPlainSocketImpl.java:106)
	at java.base/java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:437)
	at java.base/java.net.PlainSocketImpl.bind(PlainSocketImpl.java:174)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:381)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:243)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:135)
	at com.senla.main.Main.main(Main.java:17)
2018-02-16 17:27:09 TRACE Main:18 - Started, waiting for connection
2018-02-16 17:27:43 ERROR Executor:54 - Can't close resultSet
java.sql.SQLException: Column 'name' not found.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1080)
	at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5177)
	at com.senla.executor.handler.OrderHandler.handle(OrderHandler.java:22)
	at com.senla.executor.handler.OrderHandler.handle(OrderHandler.java:14)
	at com.senla.executor.Executor.execQuery(Executor.java:51)
	at com.senla.dao.GenericDao.getById(ADao.java:68)
	at OrderManager.getById(OrderManager.java:35)
	at OrderManager.getById(OrderManager.java:14)
	at Facade.getOrder(OnlineBookStore.java:147)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:28)
2018-02-16 17:27:43 ERROR ServerThread:32 - ServerThread stream is failed
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:28)
Caused by: java.lang.NullPointerException
	at com.senla.dao.GenericDao.getById(ADao.java:68)
	at OrderManager.getById(OrderManager.java:35)
	at OrderManager.getById(OrderManager.java:14)
	at Facade.getOrder(OnlineBookStore.java:147)
	... 6 more
2018-02-16 17:29:04 TRACE Main:18 - Started, waiting for connection
2018-02-16 17:29:32 ERROR Executor:54 - Can't close resultSet
java.sql.SQLException: Column 'name' not found.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1080)
	at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5177)
	at com.senla.executor.handler.OrderHandler.handle(OrderHandler.java:22)
	at com.senla.executor.handler.OrderHandler.handle(OrderHandler.java:14)
	at com.senla.executor.Executor.execQuery(Executor.java:51)
	at com.senla.dao.GenericDao.getAll(ADao.java:78)
	at OrderManager.getAll(OrderManager.java:40)
	at Facade.sortOrdersBy(OnlineBookStore.java:69)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:28)
2018-02-16 17:29:32 ERROR ServerThread:32 - ServerThread stream is failed
java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:224)
	at java.base/java.io.ObjectInputStream$PeekInputStream.peek(ObjectInputStream.java:2714)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peek(ObjectInputStream.java:3041)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:3051)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1552)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-16 17:30:16 TRACE Main:18 - Started, waiting for connection
2018-02-16 17:30:58 ERROR Executor:54 - Can't close resultSet
java.sql.SQLException: Column 'name' not found.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1080)
	at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5177)
	at com.senla.executor.handler.OrderHandler.handle(OrderHandler.java:22)
	at com.senla.executor.handler.OrderHandler.handle(OrderHandler.java:14)
	at com.senla.executor.Executor.execQuery(Executor.java:51)
	at com.senla.dao.GenericDao.getAll(ADao.java:78)
	at OrderManager.getAll(OrderManager.java:40)
	at Facade.sortOrdersBy(OnlineBookStore.java:69)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:28)
2018-02-16 17:33:15 TRACE Main:18 - Started, waiting for connection
2018-02-16 17:33:24 ERROR ServerThread:32 - ServerThread stream is failed
java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:224)
	at java.base/java.io.ObjectInputStream$PeekInputStream.peek(ObjectInputStream.java:2714)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peek(ObjectInputStream.java:3041)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:3051)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1552)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-16 17:33:35 TRACE Main:18 - Started, waiting for connection
2018-02-16 17:34:56 ERROR ServerThread:32 - ServerThread stream is failed
java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:224)
	at java.base/java.io.ObjectInputStream$PeekInputStream.peek(ObjectInputStream.java:2714)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peek(ObjectInputStream.java:3041)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:3051)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1552)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-16 17:36:39 TRACE Main:18 - Started, waiting for connection
2018-02-16 17:37:01 ERROR ServerThread:32 - ServerThread stream is failed
java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:224)
	at java.base/java.io.ObjectInputStream$PeekInputStream.peek(ObjectInputStream.java:2714)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peek(ObjectInputStream.java:3041)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:3051)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1552)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-16 17:37:17 TRACE Main:18 - Started, waiting for connection
2018-02-16 17:37:26 ERROR ServerThread:32 - ServerThread stream is failed
java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:224)
	at java.base/java.io.ObjectInputStream$PeekInputStream.peek(ObjectInputStream.java:2714)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peek(ObjectInputStream.java:3041)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:3051)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1552)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-16 17:37:38 ERROR ServerThread:32 - ServerThread stream is failed
java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:224)
	at java.base/java.io.ObjectInputStream$PeekInputStream.peek(ObjectInputStream.java:2714)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peek(ObjectInputStream.java:3041)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:3051)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1552)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-16 21:41:23 TRACE Main:18 - Started, waiting for connection
2018-02-16 22:52:25 TRACE Main:18 - Started, waiting for connection
2018-02-16 22:52:40 ERROR ServerThread:32 - ServerThread stream is failed
java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:224)
	at java.base/java.io.ObjectInputStream$PeekInputStream.peek(ObjectInputStream.java:2714)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peek(ObjectInputStream.java:3041)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:3051)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1552)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-16 22:53:00 ERROR ServerThread:32 - ServerThread stream is failed
java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:224)
	at java.base/java.io.ObjectInputStream$PeekInputStream.peek(ObjectInputStream.java:2714)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peek(ObjectInputStream.java:3041)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:3051)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1552)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-16 22:53:34 ERROR ServerThread:32 - ServerThread stream is failed
java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:224)
	at java.base/java.io.ObjectInputStream$PeekInputStream.peek(ObjectInputStream.java:2714)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peek(ObjectInputStream.java:3041)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:3051)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1552)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-16 23:01:19 TRACE Main:18 - Started, waiting for connection
2018-02-16 23:01:54 ERROR ServerThread:32 - ServerThread stream is failed
java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:224)
	at java.base/java.io.ObjectInputStream$PeekInputStream.peek(ObjectInputStream.java:2714)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peek(ObjectInputStream.java:3041)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:3051)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1552)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-17 20:37:43 TRACE Main:18 - Started, waiting for connection
2018-02-17 20:39:22 TRACE Main:18 - Started, waiting for connection
2018-02-17 20:42:39 TRACE Main:18 - Started, waiting for connection
2018-02-17 20:43:58 ERROR ServerThread:32 - ServerThread stream is failed
java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:224)
	at java.base/java.io.ObjectInputStream$PeekInputStream.peek(ObjectInputStream.java:2714)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peek(ObjectInputStream.java:3041)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:3051)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1552)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
