2017-11-18 19:17:55 ERROR Input:24 - NumberFormatException
2017-11-18 19:21:19 ERROR Input:28 - File not found
2017-11-20 19:39:26 ERROR FileWorker:26 - File not found
2017-11-24 20:49:28 ERROR Serializer:26 - File not found
2017-11-24 20:50:26 ERROR Serializer:26 - File not found
2017-11-24 20:50:28 ERROR Serializer:26 - File not found
2017-11-24 20:50:30 ERROR Serializer:26 - File not found
2017-11-24 20:50:31 ERROR Serializer:26 - File not found
2017-11-24 20:52:50 ERROR Serializer:26 - File not found
2017-11-24 20:58:05 ERROR Serializer:26 - File not found
2017-11-26 18:31:19 ERROR Serializer:26 - File not found
2017-11-26 18:31:44 ERROR Serializer:26 - File not found
2017-11-26 18:38:50 ERROR Serializer:26 - File not found
2017-11-26 18:39:19 ERROR Input:24 - NumberFormatException
2017-11-27 12:11:23 ERROR Input:23 - NumberFormatException
2017-11-27 12:18:59 ERROR Input:23 - NumberFormatException
2017-11-27 18:48:20 ERROR Input:23 - For input string: "l"
2017-11-27 18:49:29 ERROR Input:23 - For input string: "k"
2017-11-27 18:54:14 ERROR Input:23 - java.lang.NumberFormatException: For input string: "k"
2017-11-27 18:54:37 ERROR Input:23 - java.lang.NumberFormatException: For input string: "l"
2017-11-27 18:55:30 ERROR Input:23 - For input string: "o"
2017-11-29 13:11:06 ERROR Serializer:24 - com.senla.entity.Book
2017-11-29 13:11:06 ERROR Serializer:24 - com.senla.entity.Order
2017-11-29 13:11:06 ERROR Serializer:24 - com.senla.entity.Reader
2017-11-29 13:11:06 ERROR Serializer:24 - com.senla.entity.Request
2017-11-29 13:18:56 ERROR Input:23 - For input string: "l"
2017-11-29 13:18:59 ERROR Input:23 - For input string: "o"
2017-12-03 09:16:03 ERROR Input:23 - For input string: "l"
2017-12-03 09:17:00 ERROR Input:23 - For input string: "l"
2017-12-03 09:17:52 ERROR Input:23 - For input string: "l"
2017-12-03 09:18:57 ERROR Input:23 - For input string: "l"
2017-12-03 09:21:34 ERROR Serializer:26 - data\boook.bin (The system cannot find the file specified)
2017-12-03 09:22:08 ERROR Serializer:26 - data\boook.bin (The system cannot find the file specified)
2017-12-03 09:22:13 ERROR Input:23 - For input string: ""
2017-12-03 11:05:49 ERROR Input:23 - For input string: "l"
2017-12-03 19:29:45 ERROR Parser:30 - Unparseable date: "06-08-01"
2017-12-03 19:29:45 ERROR Parser:30 - Unparseable date: "01-07-99"
2017-12-03 19:29:45 ERROR Parser:30 - Unparseable date: "16-03-98"
2017-12-03 19:29:45 ERROR Parser:30 - Unparseable date: "22-07-06"
2017-12-03 19:29:45 ERROR Parser:30 - Unparseable date: "19-04-87"
2017-12-03 19:38:03 ERROR Parser:30 - Unparseable date: "06-08-01"
2017-12-03 19:38:03 ERROR Parser:30 - Unparseable date: "01-07-99"
2017-12-03 19:38:03 ERROR Parser:30 - Unparseable date: "16-03-98"
2017-12-03 19:38:03 ERROR Parser:30 - Unparseable date: "22-07-06"
2017-12-03 19:38:03 ERROR Parser:30 - Unparseable date: "19-04-87"
2017-12-03 19:41:44 ERROR CSVWorker:28 - data\bean.csv (The process cannot access the file because it is being used by another process)
2017-12-03 20:30:44 ERROR Parser:30 - Unparseable date: "06/08/2001"
2017-12-03 20:31:21 ERROR Parser:30 - Unparseable date: "01/07/1999"
2017-12-03 20:31:21 ERROR Parser:30 - Unparseable date: "16/03/1998"
2017-12-03 20:31:21 ERROR Parser:30 - Unparseable date: "22/07/2006"
2017-12-03 20:31:21 ERROR Parser:30 - Unparseable date: "19/04/1987"
2017-12-03 20:33:10 ERROR Parser:30 - Unparseable date: "06-08-01"
2017-12-03 20:33:10 ERROR Parser:30 - Unparseable date: "01-07-99"
2017-12-03 20:33:10 ERROR Parser:30 - Unparseable date: "16-03-98"
2017-12-03 20:33:10 ERROR Parser:30 - Unparseable date: "22-07-06"
2017-12-03 20:33:10 ERROR Parser:30 - Unparseable date: "19-04-87"
2017-12-03 20:35:57 ERROR Parser:30 - Unparseable date: "01-07-99"
2017-12-03 20:35:57 ERROR Parser:30 - Unparseable date: "19-04-87"
2017-12-03 20:35:57 ERROR Parser:30 - Unparseable date: "16-03-98"
2017-12-03 20:35:57 ERROR Parser:30 - Unparseable date: "22-07-06"
2017-12-03 20:35:57 ERROR Parser:30 - Unparseable date: "06-08-01"
2017-12-03 20:36:57 ERROR Parser:30 - Unparseable date: "01-07-99"
2017-12-03 20:36:57 ERROR Parser:30 - Unparseable date: "19-04-87"
2017-12-03 20:36:57 ERROR Parser:30 - Unparseable date: "16-03-98"
2017-12-03 20:36:57 ERROR Parser:30 - Unparseable date: "22-07-06"
2017-12-03 20:36:57 ERROR Parser:30 - Unparseable date: "06-08-01"
2017-12-03 20:37:20 ERROR CSVWorker:28 - data\bean.csv (The process cannot access the file because it is being used by another process)
2017-12-03 20:37:53 ERROR Parser:30 - Unparseable date: "01-07-99"
2017-12-03 20:37:53 ERROR Parser:30 - Unparseable date: "19-04-87"
2017-12-03 20:37:53 ERROR Parser:30 - Unparseable date: "16-03-98"
2017-12-03 20:37:53 ERROR Parser:30 - Unparseable date: "22-07-06"
2017-12-03 20:37:53 ERROR Parser:30 - Unparseable date: "06-08-01"
2017-12-10 12:39:33 ERROR CSVWorker:40 - data\csv\book.csv (The process cannot access the file because it is being used by another process)
2017-12-10 12:39:54 ERROR CSVWorker:44 - com.senla.model.entity.Book
2017-12-10 12:47:37 ERROR Input:23 - For input string: ""
2017-12-10 12:53:45 ERROR CSVWorker:33 - data\csv\order.csv (The process cannot access the file because it is being used by another process)
2017-12-10 12:53:52 ERROR Input:23 - For input string: ""
2017-12-12 01:03:21 ERROR DependencyInjection:33 - Class com.senla.dependencyinjection.DependencyInjection can not access a member of class com.senla.controller.dao.mysql.BookDao with modifiers "private"
2017-12-12 01:03:25 ERROR DependencyInjection:35 - Class com.senla.dependencyinjection.DependencyInjection can not access a member of class com.senla.controller.dao.mysql.BookDao with modifiers "private"
2017-12-20 09:35:21 ERROR DependencyInjection:34 - Class com.senla.dependencyinjection.DependencyInjection can not access a member of class com.senla.controller.dao.mysql.BookDao with modifiers "private"
2017-12-20 09:35:21 ERROR DependencyInjection:34 - Class com.senla.dependencyinjection.DependencyInjection can not access a member of class com.senla.controller.dao.mysql.ReaderDao with modifiers "private"
2017-12-20 09:35:21 ERROR DependencyInjection:34 - Class com.senla.dependencyinjection.DependencyInjection can not access a member of class com.senla.controller.dao.mysql.OrderDao with modifiers "private"
2017-12-20 09:35:21 ERROR DependencyInjection:34 - Class com.senla.dependencyinjection.DependencyInjection can not access a member of class com.senla.controller.dao.mysql.RequestDao with modifiers "private"
2017-12-20 09:36:19 ERROR DependencyInjection:34 - Class com.senla.dependencyinjection.DependencyInjection can not access a member of class com.senla.controller.dao.mysql.ReaderDao with modifiers "private"
2017-12-20 09:36:19 ERROR DependencyInjection:34 - Class com.senla.dependencyinjection.DependencyInjection can not access a member of class com.senla.controller.dao.mysql.OrderDao with modifiers "private"
2017-12-20 09:36:19 ERROR DependencyInjection:34 - Class com.senla.dependencyinjection.DependencyInjection can not access a member of class com.senla.controller.dao.mysql.RequestDao with modifiers "private"
2017-12-20 09:45:04 ERROR DependencyInjection:41 - Class com.senla.dependencyinjection.DependencyInjection can not access a member of class com.senla.controller.dao.mysql.BookDao with modifiers "private"
2017-12-20 09:45:04 ERROR DependencyInjection:41 - Class com.senla.dependencyinjection.DependencyInjection can not access a member of class com.senla.controller.dao.mysql.ReaderDao with modifiers "private"
2017-12-20 09:45:04 ERROR DependencyInjection:41 - Class com.senla.dependencyinjection.DependencyInjection can not access a member of class com.senla.controller.dao.mysql.OrderDao with modifiers "private"
2017-12-20 09:45:04 ERROR DependencyInjection:41 - Class com.senla.dependencyinjection.DependencyInjection can not access a member of class com.senla.controller.dao.mysql.RequestDao with modifiers "private"
2017-12-28 21:21:19 ERROR CSVWorker:154 - com.senla.model.entity.Book.<init>()
2017-12-28 21:22:31 ERROR CSVWorker:154 - com.senla.model.entity.Book.<init>()
2017-12-28 21:23:18 ERROR CSVWorker:154 - com.senla.model.entity.Book.<init>()
2017-12-28 21:29:10 ERROR CSVWorker:154 - com.senla.model.entity.Book.<init>()
2017-12-28 21:37:53 ERROR CSVWorker:154 - com.senla.model.entity.Book.<init>()
2017-12-28 21:38:27 ERROR CSVWorker:156 - com.senla.model.entity.Book.<init>()
2017-12-28 21:42:25 ERROR CSVWorker:156 - com.senla.model.entity.Book.<init>()
2017-12-28 21:42:52 ERROR CSVWorker:156 - com.senla.model.entity.Book.<init>()
2017-12-28 21:44:49 ERROR CSVWorker:156 - [Ljava.lang.StackTraceElement;@523884b2
2017-12-28 21:47:28 ERROR CSVWorker:155 - com.senla.model.entity.Book.<init>()
2017-12-28 21:50:05 ERROR CSVWorker:155 - com.senla.model.entity.Book.<init>()
2017-12-28 21:51:44 ERROR CSVWorker:156 - com.senla.model.entity.Book
2017-12-28 21:53:23 ERROR CSVWorker:156 - com.senla.model.entity.Book
2017-12-28 21:54:22 ERROR CSVWorker:156 - Can not set int field com.senla.model.entity.Book.price to java.lang.String
2017-12-28 21:57:18 ERROR CSVWorker:154 - Can not set int field com.senla.model.entity.Book.price to java.lang.String
2017-12-28 22:04:38 ERROR CSVWorker:152 - Can not set int field com.senla.model.entity.Book.price to java.lang.String
2017-12-28 22:05:08 ERROR CSVWorker:152 - Can not set int field com.senla.model.entity.Book.price to java.lang.String
2017-12-28 22:08:31 ERROR CSVWorker:152 - Can not set int field com.senla.model.entity.Book.price to java.lang.String
2017-12-28 22:09:51 ERROR CSVWorker:152 - java.lang.Integer.parseInteger(java.lang.String)
2017-12-28 22:10:19 ERROR CSVWorker:152 - java.lang.Integer.parseInteger(java.lang.String)
2017-12-28 22:24:30 ERROR CSVWorker:152 - java.lang.Integer.parseInteger(java.lang.String)
2017-12-28 22:25:24 ERROR CSVWorker:140 - For input string: "false"
2017-12-28 22:32:06 ERROR CSVWorker:144 - For input string: "false"
2017-12-28 22:33:17 ERROR CSVWorker:144 - For input string: "false"
2017-12-28 22:33:24 ERROR CSVWorker:145 - For input string: "false"
2017-12-28 22:39:02 ERROR CSVWorker:145 - For input string: "false"
2017-12-28 23:52:56 ERROR Parser:59 - For input string: "true"
2018-02-11 01:23:59 ERROR DaoFactory:39 - Database Connection Creation Failed: 
java.sql.SQLException: No suitable driver found for "jdbc:mysql://localhost:3306/book_shop?autoReconnect=true&useSSL=false";
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:703)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
	at com.senla.controller.dao.DaoFactory.<init>(DaoFactory.java:36)
	at com.senla.controller.dao.DaoFactory.getInstance(DaoFactory.java:17)
	at com.senla.controller.manager.BookManager.<init>(BookManager.java:19)
	at com.senla.view.facade.OnlineBookStore.<init>(OnlineBookStore.java:20)
	at com.senla.view.facade.OnlineBookStore.getInstance(OnlineBookStore.java:29)
	at com.senla.main.Main.main(Main.java:14)
2018-02-11 01:23:59 ERROR DependencyInjection:36 - 
2018-02-11 01:33:59 ERROR DaoFactory:41 - Database Connection Creation Failed: 
java.sql.SQLException: No suitable driver found for "jdbc:mysql://localhost:3306/book_shop?autoReconnect=true&useSSL=false";
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:703)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
	at com.senla.controller.dao.DaoFactory.<init>(DaoFactory.java:38)
	at com.senla.controller.dao.DaoFactory.getInstance(DaoFactory.java:18)
	at com.senla.controller.manager.BookManager.<init>(BookManager.java:19)
	at com.senla.view.facade.OnlineBookStore.<init>(OnlineBookStore.java:20)
	at com.senla.view.facade.OnlineBookStore.getInstance(OnlineBookStore.java:29)
	at com.senla.main.Main.main(Main.java:14)
2018-02-11 01:33:59 ERROR DependencyInjection:36 - 
2018-02-11 01:37:16 ERROR DaoFactory:41 - Database Connection Creation Failed: 
java.sql.SQLException: No suitable driver found for "jdbc:mysql://localhost:3306/book_shop?autoReconnect=true&useSSL=false";
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:703)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
	at com.senla.controller.dao.DaoFactory.<init>(DaoFactory.java:38)
	at com.senla.controller.dao.DaoFactory.getInstance(DaoFactory.java:18)
	at com.senla.controller.manager.BookManager.<init>(BookManager.java:19)
	at com.senla.view.facade.OnlineBookStore.<init>(OnlineBookStore.java:20)
	at com.senla.view.facade.OnlineBookStore.getInstance(OnlineBookStore.java:29)
	at com.senla.main.Main.main(Main.java:14)
2018-02-11 01:37:16 ERROR DependencyInjection:36 - 
2018-02-11 01:40:02 ERROR DaoFactory:42 - Database Connection Creation Failed: 
java.sql.SQLException: No suitable driver found for "jdbc:mysql://localhost:3306/book_shop?autoReconnect=true&useSSL=false";
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:703)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
	at com.senla.controller.dao.DaoFactory.<init>(DaoFactory.java:39)
	at com.senla.controller.dao.DaoFactory.getInstance(DaoFactory.java:19)
	at com.senla.controller.manager.BookManager.<init>(BookManager.java:19)
	at com.senla.view.facade.OnlineBookStore.<init>(OnlineBookStore.java:20)
	at com.senla.view.facade.OnlineBookStore.getInstance(OnlineBookStore.java:29)
	at com.senla.main.Main.main(Main.java:14)
2018-02-11 01:40:02 ERROR DependencyInjection:36 - 
2018-02-11 02:08:42 ERROR Executor:32 - Can't close statement
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1184)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1179)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2355)
	at com.senla.executor.Executor.execQuery(Executor.java:24)
	at com.senla.controller.manager.BookManager.sortBooks(BookManager.java:54)
	at com.senla.view.facade.OnlineBookStore.sortBooksBy(OnlineBookStore.java:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 09:37:14 ERROR Main:26 - Failed socket connection
java.net.BindException: Address already in use: NET_Bind
	at java.base/java.net.DualStackPlainSocketImpl.bind0(Native Method)
	at java.base/java.net.DualStackPlainSocketImpl.socketBind(DualStackPlainSocketImpl.java:106)
	at java.base/java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:437)
	at java.base/java.net.PlainSocketImpl.bind(PlainSocketImpl.java:174)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:381)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:243)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:135)
	at com.senla.main.Main.main(Main.java:17)
2018-02-11 09:37:34 ERROR Main:26 - Failed socket connection
java.net.BindException: Address already in use: NET_Bind
	at java.base/java.net.DualStackPlainSocketImpl.bind0(Native Method)
	at java.base/java.net.DualStackPlainSocketImpl.socketBind(DualStackPlainSocketImpl.java:106)
	at java.base/java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:437)
	at java.base/java.net.PlainSocketImpl.bind(PlainSocketImpl.java:174)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:381)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:243)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:135)
	at com.senla.main.Main.main(Main.java:17)
2018-02-11 09:42:36 TRACE Main:19 - Started, waiting for connection
2018-02-11 09:42:54 TRACE Main:18 - Started, waiting for connection
2018-02-11 09:43:13 ERROR Main:25 - Failed socket connection
java.net.BindException: Address already in use: NET_Bind
	at java.base/java.net.DualStackPlainSocketImpl.bind0(Native Method)
	at java.base/java.net.DualStackPlainSocketImpl.socketBind(DualStackPlainSocketImpl.java:106)
	at java.base/java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:437)
	at java.base/java.net.PlainSocketImpl.bind(PlainSocketImpl.java:174)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:381)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:243)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:135)
	at com.senla.main.Main.main(Main.java:17)
2018-02-11 09:43:28 TRACE Main:18 - Started, waiting for connection
2018-02-11 10:33:38 TRACE Main:18 - Started, waiting for connection
2018-02-11 12:28:23 TRACE Main:18 - Started, waiting for connection
2018-02-11 14:20:59 TRACE Main:18 - Started, waiting for connection
2018-02-11 14:21:13 ERROR Executor:29 - Can't close result
java.sql.SQLException: Column 'orderId' not found.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1080)
	at com.mysql.jdbc.ResultSetImpl.getInt(ResultSetImpl.java:2570)
	at com.senla.executor.handler.BookHandler.handle(BookHandler.java:33)
	at com.senla.executor.handler.BookHandler.handle(BookHandler.java:13)
	at com.senla.executor.Executor.execQuery(Executor.java:27)
	at com.senla.controller.manager.BookManager.sortBooks(BookManager.java:60)
	at com.senla.view.facade.OnlineBookStore.sortBooksBy(OnlineBookStore.java:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 14:21:46 ERROR OrderManager:79 - Can't close
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1184)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1179)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2355)
	at com.senla.controller.manager.OrderManager.getAmountExecutedOrders(OrderManager.java:71)
	at com.senla.view.facade.OnlineBookStore.getAmountExecutedOrders(OnlineBookStore.java:181)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:19)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 14:21:56 ERROR OrderManager:60 - Can't close
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1184)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1179)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2355)
	at com.senla.controller.manager.OrderManager.getAllPrice(OrderManager.java:52)
	at com.senla.view.facade.OnlineBookStore.getAllPrice(OnlineBookStore.java:176)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:19)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 14:22:03 ERROR Executor:32 - Can't close statement
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1184)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1179)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2355)
	at com.senla.executor.Executor.execQuery(Executor.java:24)
	at com.senla.controller.manager.OrderManager.sortOrders(OrderManager.java:96)
	at com.senla.view.facade.OnlineBookStore.sortOrdersBy(OnlineBookStore.java:73)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 14:22:34 TRACE Main:18 - Started, waiting for connection
2018-02-11 14:22:49 TRACE Main:18 - Started, waiting for connection
2018-02-11 14:23:43 TRACE Main:18 - Started, waiting for connection
2018-02-11 14:23:57 ERROR Executor:32 - Can't close statement
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1184)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1179)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2355)
	at com.senla.executor.Executor.execQuery(Executor.java:24)
	at com.senla.controller.manager.BookManager.sortBooks(BookManager.java:60)
	at com.senla.view.facade.OnlineBookStore.sortBooksBy(OnlineBookStore.java:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 14:24:16 TRACE Main:18 - Started, waiting for connection
2018-02-11 14:24:23 ERROR Executor:32 - Can't close statement
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1184)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1179)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2355)
	at com.senla.executor.Executor.execQuery(Executor.java:24)
	at com.senla.controller.manager.BookManager.sortBooks(BookManager.java:60)
	at com.senla.view.facade.OnlineBookStore.sortBooksBy(OnlineBookStore.java:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 14:24:48 TRACE Main:18 - Started, waiting for connection
2018-02-11 14:24:54 TRACE Main:18 - Started, waiting for connection
2018-02-11 14:25:44 TRACE Main:18 - Started, waiting for connection
2018-02-11 14:26:00 ERROR Executor:32 - Can't close statement
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1184)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1179)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2355)
	at com.senla.executor.Executor.execQuery(Executor.java:24)
	at com.senla.controller.manager.BookManager.sortBooks(BookManager.java:60)
	at com.senla.view.facade.OnlineBookStore.sortBooksBy(OnlineBookStore.java:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 14:26:39 ERROR Executor:32 - Can't close statement
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1184)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1179)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2355)
	at com.senla.executor.Executor.execQuery(Executor.java:24)
	at com.senla.controller.manager.BookManager.sortBooks(BookManager.java:60)
	at com.senla.view.facade.OnlineBookStore.sortBooksBy(OnlineBookStore.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 14:27:50 ERROR Executor:32 - Can't close statement
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1184)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1179)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2355)
	at com.senla.executor.Executor.execQuery(Executor.java:24)
	at com.senla.controller.manager.BookManager.sortBooks(BookManager.java:60)
	at com.senla.view.facade.OnlineBookStore.sortBooksBy(OnlineBookStore.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 14:30:05 TRACE Main:18 - Started, waiting for connection
2018-02-11 14:30:14 TRACE BookManager:57 - Open connection
2018-02-11 14:30:14 ERROR Executor:29 - Can't close result
java.sql.SQLException: Column 'orderId' not found.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1080)
	at com.mysql.jdbc.ResultSetImpl.getInt(ResultSetImpl.java:2570)
	at com.senla.executor.handler.BookHandler.handle(BookHandler.java:33)
	at com.senla.executor.handler.BookHandler.handle(BookHandler.java:13)
	at com.senla.executor.Executor.execQuery(Executor.java:27)
	at com.senla.controller.manager.BookManager.sortBooks(BookManager.java:60)
	at com.senla.view.facade.OnlineBookStore.sortBooksBy(OnlineBookStore.java:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 14:31:19 TRACE Main:18 - Started, waiting for connection
2018-02-11 14:31:37 TRACE BookManager:57 - Open connection
2018-02-11 14:31:37 ERROR Executor:32 - Can't close statement
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1184)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1179)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2371)
	at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2355)
	at com.senla.executor.Executor.execQuery(Executor.java:24)
	at com.senla.controller.manager.BookManager.sortBooks(BookManager.java:60)
	at com.senla.view.facade.OnlineBookStore.sortBooksBy(OnlineBookStore.java:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 14:33:52 TRACE Main:18 - Started, waiting for connection
2018-02-11 14:33:52 ERROR Main:25 - Failed socket connection
java.net.SocketException: Connection reset by peer: socket write error
	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at java.base/java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1883)
	at java.base/java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(ObjectOutputStream.java:1792)
	at java.base/java.io.ObjectOutputStream.<init>(ObjectOutputStream.java:248)
	at com.senla.main.ServerThread.<init>(ServerThread.java:18)
	at com.senla.main.Main.main(Main.java:21)
2018-02-11 14:33:54 TRACE Main:18 - Started, waiting for connection
2018-02-11 14:34:23 ERROR Main:25 - Failed socket connection
java.net.BindException: Address already in use: NET_Bind
	at java.base/java.net.DualStackPlainSocketImpl.bind0(Native Method)
	at java.base/java.net.DualStackPlainSocketImpl.socketBind(DualStackPlainSocketImpl.java:106)
	at java.base/java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:437)
	at java.base/java.net.PlainSocketImpl.bind(PlainSocketImpl.java:174)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:381)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:243)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:135)
	at com.senla.main.Main.main(Main.java:17)
2018-02-11 14:34:27 TRACE Main:18 - Started, waiting for connection
2018-02-11 14:34:34 TRACE BookManager:57 - Open connection
2018-02-11 14:35:55 ERROR Executor:29 - Can't close result
java.sql.SQLException: Column 'orderId' not found.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1080)
	at com.mysql.jdbc.ResultSetImpl.getInt(ResultSetImpl.java:2570)
	at com.senla.executor.handler.BookHandler.handle(BookHandler.java:33)
	at com.senla.executor.handler.BookHandler.handle(BookHandler.java:13)
	at com.senla.executor.Executor.execQuery(Executor.java:27)
	at com.senla.controller.manager.BookManager.sortBooks(BookManager.java:60)
	at com.senla.view.facade.OnlineBookStore.sortBooksBy(OnlineBookStore.java:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 14:37:47 TRACE Main:18 - Started, waiting for connection
2018-02-11 14:37:55 TRACE BookManager:57 - Open connection
2018-02-11 14:37:55 ERROR Executor:29 - Can't close result
java.sql.SQLException: Column 'readerId' not found.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1080)
	at com.mysql.jdbc.ResultSetImpl.getInt(ResultSetImpl.java:2570)
	at com.senla.executor.handler.BookHandler.handle(BookHandler.java:42)
	at com.senla.executor.handler.BookHandler.handle(BookHandler.java:13)
	at com.senla.executor.Executor.execQuery(Executor.java:27)
	at com.senla.controller.manager.BookManager.sortBooks(BookManager.java:60)
	at com.senla.view.facade.OnlineBookStore.sortBooksBy(OnlineBookStore.java:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 14:45:01 TRACE Main:18 - Started, waiting for connection
2018-02-11 14:45:06 TRACE BookManager:57 - Open connection
2018-02-11 15:36:48 TRACE Main:18 - Started, waiting for connection
2018-02-11 15:37:23 TRACE OrderManager:93 - Open connection
2018-02-11 15:37:23 ERROR Executor:29 - Can't close result
java.sql.SQLException: Column 'name' not found.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1080)
	at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5177)
	at com.senla.executor.handler.OrderHandler.handle(OrderHandler.java:41)
	at com.senla.executor.handler.OrderHandler.handle(OrderHandler.java:14)
	at com.senla.executor.Executor.execQuery(Executor.java:27)
	at com.senla.controller.manager.OrderManager.sortOrders(OrderManager.java:96)
	at com.senla.view.facade.OnlineBookStore.sortOrdersBy(OnlineBookStore.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
2018-02-11 15:42:58 TRACE Main:18 - Started, waiting for connection
2018-02-11 15:43:08 TRACE OrderManager:93 - Open connection
2018-02-11 15:43:08 ERROR Executor:29 - Can't close result
java.sql.SQLException: Column 'name' not found.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1080)
	at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5177)
	at com.senla.executor.handler.OrderHandler.handle(OrderHandler.java:41)
	at com.senla.executor.handler.OrderHandler.handle(OrderHandler.java:14)
	at com.senla.executor.Executor.execQuery(Executor.java:27)
	at com.senla.controller.manager.OrderManager.sortOrders(OrderManager.java:96)
	at com.senla.view.facade.OnlineBookStore.sortOrdersBy(OnlineBookStore.java:73)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.senla.util.MethodInvoker.getResponse(MethodInvoker.java:22)
	at com.senla.main.ServerThread.run(ServerThread.java:27)
